---
- name: Install python
  package:
    name: [python-minimal, python-setuptools, python-pip]
    state: present
  when: ansible_python.version.major==2

- name: Install pip3 when python verison > 3
  package:
    name: python3-pip
    state: present
  when: ansible_python.version.major==3

- name: Install packages for ansible
  pip:
    name: [docker]
    state: present

- name: Allow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"
    state: present
  notify: restart ssh

- include_tasks: single_bastion.yml
  when: multi_bastion == false

- include_tasks: multi_bastion.yml
  when: multi_bastion == true
